# Generated by Django 2.1 on 2021-05-18 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastpaidmonth', models.CharField(max_length=10)),
                ('duetobepaid', models.IntegerField()),
            ],
            options={
                'db_table': 'fees_db',
            },
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=10)),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('DateOfAdmission', models.DateField()),
                ('regNo', models.CharField(max_length=20)),
                ('perAddress', models.CharField(max_length=30)),
                ('tempAddress', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('ParentCont', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('FatherName', models.CharField(max_length=20)),
                ('GrandFatherName', models.CharField(max_length=20)),
                ('profileImg', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'students_db',
            },
        ),
        migrations.CreateModel(
            name='usersaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'useraccounts_db',
            },
        ),
        migrations.AddField(
            model_name='fees',
            name='studentss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.students'),
        ),
    ]
