# Generated by Django 2.1 on 2021-05-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='regNo',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
