# Generated by Django 2.1 on 2021-05-18 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_fees_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='studentss',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Accounts.students'),
        ),
    ]
