# Generated by Django 2.1 on 2021-05-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210518_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='studentss',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.Fees'),
        ),
    ]
