# Generated by Django 2.1 on 2021-05-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20210518_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='studentss',
        ),
        migrations.AddField(
            model_name='fees',
            name='studentss',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.students'),
        ),
    ]
