# Generated by Django 2.1 on 2021-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryusermodel',
            name='L_ID',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='libraryusermodel',
            name='address',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='libraryusermodel',
            name='contact',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='libraryusermodel',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='libraryusermodel',
            name='fullname',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
