# Generated by Django 2.1 on 2021-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_auto_20210528_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryusermodel',
            name='L_ID',
            field=models.CharField(max_length=10),
        ),
    ]
