# Generated by Django 2.1 on 2021-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_auto_20210528_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryusermodel',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='libraryusermodel',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libraryusermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='libraryusermodel',
            name='fullname',
            field=models.CharField(max_length=20),
        ),
    ]
